<script>
  import imgIpv6 from '$lib/assets/ipv6/ipv6.webp';
</script>

<svelte:head>
	<title>PeerLens IPv6 Candidate Details</title>
</svelte:head>

<div class="page">
  <div class="card">
    <section class="hero mb-7">
      <div class="grid gap-6">
        <p class="eyebrow">IPv6 details</p>
        <h1>About global 2003 IPv6 ICE candidates</h1>
        <p class="lede">
          During WebRTC setup, your browser may share a global IPv6 address (often beginning with <strong>2003:</strong>)
          as an ICE candidate. We cannot control what kind of IP your browser is offering us.
        </p>
      </div>
  
      <div class="hero-visual" aria-hidden="true">
        <img src="{imgIpv6}" alt="Illustration of IPv6 connectivity" />
      </div>
    </section>
    <p class="lede mb-0">
      PeerLens uses that only to negotiate a direct connection between your phone and viewer. We do not keep that
      address as stored user data, check our <a class="link" href="/data">data section</a>.
    </p>
  </div>

	<section class="card">
		<h2 class="section-title">What happens in PeerLens</h2>

		<div class="subtle-card">
			<div>
				<h3>1) The candidate is generated by your device</h3>
				<p>
					Your browser builds a list of possible network paths (<a class="link" href="/data#ice">ICE candidates</a>). One of these can be your global
					IPv6 address.
				</p>
			</div>
		</div>

		<div class="subtle-card">
			<div>
				<h3>2) PeerLens relays it during negotiation</h3>
				<p>
					The candidate is exchanged through the temporary signaling session so the two devices can find a working
					direct route.
				</p>
			</div>
		</div>

		<div class="subtle-card">
			<div>
				<h3>3) It may exist briefly in our DB</h3>
				<p>
					Because signaling is asynchronous, that candidate can sit in the database for a short window (usually a
					few seconds) before it is consumed and cleaned up.
				</p>
			</div>
		</div>

		<div class="subtle-card">
			<div>
				<h3>4) Media stays peer-to-peer</h3>
				<p class="mb-0">
					After negotiation, your video stream goes directly from phone to viewer.<br>
					The IP gets deleted from our servers.
				</p>
			</div>
		</div>
	</section>

	<section class="card">
		<h2 class="section-title">What this IP could reveal in theory</h2>
		<p>
			This section explains theoretical capability only. PeerLens is not using the address for profiling,
			tracking, or analytics.
		</p>

		<div class="theory-grid" aria-label="Theoretical IPv6 side effects">
			<div class="subtle-card">
        <div class="icon-chip">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="100%" height="100%" color="currentColor" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="round" stroke-linejoin="round">
            <path d="M22 10V9.21749C22 7.27787 22 6.30807 21.4142 5.7055C20.8284 5.10294 19.8856 5.10294 18 5.10294H15.9214C15.004 5.10294 14.9964 5.10116 14.1715 4.68834L10.8399 3.02114C9.44884 2.32504 8.75332 1.97699 8.01238 2.00118C7.27143 2.02537 6.59877 2.41808 5.25345 3.20351L4.02558 3.92037C3.03739 4.49729 2.54329 4.78576 2.27164 5.26564C2 5.74553 2 6.32993 2 7.49873V15.7157C2 17.2514 2 18.0193 2.34226 18.4467C2.57001 18.731 2.88916 18.9222 3.242 18.9856C3.77226 19.0808 4.42148 18.7018 5.71987 17.9437C6.60156 17.429 7.45011 16.8944 8.50487 17.0394C9.38869 17.1608 10.21 17.7185 11 18.1138" />
            <path d="M8 2L8 17" />
            <path d="M15 5V9.5" />
            <path d="M18.3083 21.6835C18.0915 21.8865 17.8017 22 17.5001 22C17.1985 22 16.9087 21.8865 16.6919 21.6835C14.7063 19.813 12.0455 17.7235 13.3431 14.6898C14.0447 13.0496 15.7289 12 17.5001 12C19.2713 12 20.9555 13.0496 21.6571 14.6898C22.9531 17.7196 20.2988 19.8194 18.3083 21.6835Z" />
            <path d="M17.5 16.5H17.509" />
          </svg>
        </div>
        <div>
          <h3>Approximate location</h3>
          <p>
            At most, an IP can sometimes suggest rough geography (often ISP region/city level), not a precise street
            address.
          </p>
        </div>
			</div>

			<div class="subtle-card">
        <div class="icon-chip">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="100%" height="100%" color="currentColor" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="round" stroke-linejoin="round">
            <path d="M9 22L6 15L3 22H9Z" />
            <path d="M18.1917 13.3352C19.4847 14.6282 20.1312 15.2747 19.9778 16.2732C19.9707 16.3193 19.9548 16.3994 19.9437 16.4447C19.7033 17.4259 19.0448 17.6987 17.7276 18.2443C16.5231 18.7432 15.2321 19 13.9283 19C12.6245 19 11.3334 18.7432 10.1289 18.2443C8.92433 17.7453 7.82984 17.014 6.90792 16.0921C5.986 15.1702 5.25468 14.0757 4.75574 12.8711C4.2568 11.6666 4 10.3755 4 9.07173C4 7.76794 4.2568 6.4769 4.75575 5.27235C5.30131 3.95524 5.5741 3.29668 6.55528 3.05633C6.60061 3.04523 6.68071 3.0293 6.72683 3.02221C7.72531 2.86878 8.3718 3.51527 9.66479 4.80826L18.1917 13.3352Z" />
            <circle cx="19" cy="4" r="2" />
            <path d="M12.5 7.13288L17.7134 5.5293L15.8766 10.5293" />
          </svg>
        </div>
        <div>
          <h3>ISP / network attribution</h3>
          <p>
            The prefix can indicate which provider or organization owns that network block.
          </p>
        </div>
			</div>

			<div class="subtle-card">
        <div class="icon-chip">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="100%" height="100%" color="currentColor" fill="none" stroke="currentCOlor" stroke-width="1" stroke-linecap="round">
            <path d="M10 13.229C10.1416 13.4609 10.3097 13.6804 10.5042 13.8828C11.7117 15.1395 13.5522 15.336 14.9576 14.4722C15.218 14.3121 15.4634 14.1157 15.6872 13.8828L18.9266 10.5114C20.3578 9.02184 20.3578 6.60676 18.9266 5.11718C17.4953 3.6276 15.1748 3.62761 13.7435 5.11718L13.03 5.85978" />
            <path d="M10.9703 18.14L10.2565 18.8828C8.82526 20.3724 6.50471 20.3724 5.07345 18.8828C3.64218 17.3932 3.64218 14.9782 5.07345 13.4886L8.31287 10.1172C9.74413 8.62761 12.0647 8.6276 13.4959 10.1172C13.6904 10.3195 13.8584 10.539 14 10.7708" />
          </svg>
        </div>
        <div>
          <h3>Short-term correlation risk</h3>
          <p>
            If the same address appears repeatedly, it could theoretically be used to correlate sessions within a
            limited time window.
          </p>
        </div>
			</div>

			<div class="subtle-card">
        <div class="icon-chip">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="100%" height="100%" color="currentColor" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="round" stroke-linejoin="round">
            <path d="M12 16.9995C16.2266 16.9995 18.3342 13.5086 18.913 12.3606C19.0289 12.1308 19.0289 11.8682 18.913 11.6384C18.3342 10.4904 16.2266 6.99951 12 6.99951C7.77333 6.99951 5.6657 10.4904 5.08686 11.6384C4.97099 11.8682 4.97099 12.1308 5.08686 12.3606C5.6657 13.5086 7.77333 16.9995 12 16.9995Z" />
            <circle cx="12" cy="11.9995" r="2" />
            <path d="M21.5 7.50034C21.4085 5.6542 21.1348 4.50316 20.316 3.68435C19.4972 2.86555 18.3462 2.59184 16.5 2.50034M2.50002 7.49951C2.59151 5.65337 2.86522 4.50233 3.68403 3.68352C4.50284 2.86472 5.65387 2.59101 7.50002 2.49951M21.5 16.4998C21.4085 18.3459 21.1348 19.497 20.316 20.3158C19.4972 21.1346 18.3462 21.4083 16.5 21.4998M2.50002 16.5006C2.59151 18.3468 2.86522 19.4978 3.68403 20.3166C4.50284 21.1354 5.65387 21.4091 7.50002 21.5006" />
          </svg>
        </div>
        <div>
          <h3>Potential targeting surface</h3>
          <p>
            As with any internet-reachable IP, it could be treated as a target for scans in theory, though real
            reachability depends on router and firewall settings.
          </p>
        </div>
			</div>
		</div>
	</section>

	<section class="card safety-card" aria-labelledby="we-do-not-do-title">
		<h2 class="section-title" id="we-do-not-do-title">What PeerLens does not do</h2>
		<ul>
			<li>We do not build user profiles from IP addresses.</li>
			<li>We do not sell or share this data for marketing.</li>
			<li>We do not persist ICE candidates as long-term analytics data.</li>
			<li>We do not record your video stream.</li>
		</ul>
	</section>

	<section class="card">
		<h2 class="section-title">Practical mitigations (if you want extra privacy)</h2>
		<ul>
			<li>Use trusted local networks for sessions.</li>
			<li>Avoid posting session links/QR codes publicly.</li>
			<li>Keep your router and firewall defaults enabled.</li>
			<li>Use temporary/private-address features on your devices when available.</li>
		</ul>
		<p class="mb-0">
			If you want, we can also explain this behavior in a short tooltip on the session page so users see it before
			connecting.
		</p>
	</section>
</div>

<style>
	.theory-grid {
		display: grid;
		grid-template-columns: repeat(2, minmax(0, 1fr));
		gap: 1rem;
	}
	.theory-grid .subtle-card {
		margin-bottom: 0;
	}

	.safety-card {
		display: grid;
		gap: 0.4rem;
		border-color: color-mix(in srgb, #7a1010 45%, var(--primary) 55%);
		background: color-mix(in srgb, #7a1010 10%, rgba(3, 76, 83, 0.4) 90%);
	}

	@media (max-width: 760px) {
		.theory-grid {
			grid-template-columns: 1fr;
		}
	}
</style>
